// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enums.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HandControl.Model.Protobuf {

  /// <summary>Holder for reflection information generated from enums.proto</summary>
  public static partial class EnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for enums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtlbnVtcy5wcm90bxIFZW51bXMqpQEKEE1vZHVsZVN0YXR1c1R5cGUSIAoc",
            "TU9EVUxFX1NUQVRVU19JTklUSUFMSVpBVElPThAAEhYKEk1PRFVMRV9TVEFU",
            "VVNfV09SSxABEhcKE01PRFVMRV9TVEFUVVNfRVJST1IQAhIiCh5NT0RVTEVf",
            "U1RBVFVTX0NPTk5FQ1RJT05fRVJST1IQAxIaChZNT0RVTEVfU1RBVFVTX0RJ",
            "U0FCTEVEEAQqygEKEERyaXZlclN0YXR1c1R5cGUSIAocRFJJVkVSX1NUQVRV",
            "U19JTklUSUFMSVpBVElPThAAEhcKE0RSSVZFUl9TVEFUVVNfRVJST1IQARIi",
            "Ch5EUklWRVJfU1RBVFVTX0NPTk5FQ1RJT05fRVJST1IQAhIaChZEUklWRVJf",
            "U1RBVFVTX0RJU0FCTEVEEAMSFwoTRFJJVkVSX1NUQVRVU19TTEVFUBAEEiIK",
            "HkRSSVZFUl9TVEFUVVNfU0VUVElOR19QT1NJVElPThAFQh2qAhpIYW5kQ29u",
            "dHJvbC5Nb2RlbC5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HandControl.Model.Protobuf.ModuleStatusType), typeof(global::HandControl.Model.Protobuf.DriverStatusType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ModuleStatusType {
    [pbr::OriginalName("MODULE_STATUS_INITIALIZATION")] ModuleStatusInitialization = 0,
    [pbr::OriginalName("MODULE_STATUS_WORK")] ModuleStatusWork = 1,
    [pbr::OriginalName("MODULE_STATUS_ERROR")] ModuleStatusError = 2,
    [pbr::OriginalName("MODULE_STATUS_CONNECTION_ERROR")] ModuleStatusConnectionError = 3,
    [pbr::OriginalName("MODULE_STATUS_DISABLED")] ModuleStatusDisabled = 4,
  }

  public enum DriverStatusType {
    [pbr::OriginalName("DRIVER_STATUS_INITIALIZATION")] DriverStatusInitialization = 0,
    [pbr::OriginalName("DRIVER_STATUS_ERROR")] DriverStatusError = 1,
    [pbr::OriginalName("DRIVER_STATUS_CONNECTION_ERROR")] DriverStatusConnectionError = 2,
    [pbr::OriginalName("DRIVER_STATUS_DISABLED")] DriverStatusDisabled = 3,
    [pbr::OriginalName("DRIVER_STATUS_SLEEP")] DriverStatusSleep = 4,
    [pbr::OriginalName("DRIVER_STATUS_SETTING_POSITION")] DriverStatusSettingPosition = 5,
  }

  #endregion

}

#endregion Designer generated code
