// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enums.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HandControl.Model.Protobuf {

  /// <summary>Holder for reflection information generated from enums.proto</summary>
  public static partial class EnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for enums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtlbnVtcy5wcm90bxIFZW51bXMqOgoITW9kZVR5cGUSDAoITU9ERV9NSU8Q",
            "ABIRCg1NT0RFX0NPTU1BTkRTEAESDQoJTU9ERV9BVVRPEAIqpQEKEE1vZHVs",
            "ZVN0YXR1c1R5cGUSIAocTU9EVUxFX1NUQVRVU19JTklUSUFMSVpBVElPThAA",
            "EhYKEk1PRFVMRV9TVEFUVVNfV09SSxABEhcKE01PRFVMRV9TVEFUVVNfRVJS",
            "T1IQAhIiCh5NT0RVTEVfU1RBVFVTX0NPTk5FQ1RJT05fRVJST1IQAxIaChZN",
            "T0RVTEVfU1RBVFVTX0RJU0FCTEVEEAQqygEKEERyaXZlclN0YXR1c1R5cGUS",
            "IAocRFJJVkVSX1NUQVRVU19JTklUSUFMSVpBVElPThAAEhcKE0RSSVZFUl9T",
            "VEFUVVNfRVJST1IQARIiCh5EUklWRVJfU1RBVFVTX0NPTk5FQ1RJT05fRVJS",
            "T1IQAhIaChZEUklWRVJfU1RBVFVTX0RJU0FCTEVEEAMSFwoTRFJJVkVSX1NU",
            "QVRVU19TTEVFUBAEEiIKHkRSSVZFUl9TVEFUVVNfU0VUVElOR19QT1NJVElP",
            "ThAFQh2qAhpIYW5kQ29udHJvbC5Nb2RlbC5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HandControl.Model.Protobuf.ModeType), typeof(global::HandControl.Model.Protobuf.ModuleStatusType), typeof(global::HandControl.Model.Protobuf.DriverStatusType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ModeType {
    [pbr::OriginalName("MODE_MIO")] ModeMio = 0,
    [pbr::OriginalName("MODE_COMMANDS")] ModeCommands = 1,
    [pbr::OriginalName("MODE_AUTO")] ModeAuto = 2,
  }

  public enum ModuleStatusType {
    [pbr::OriginalName("MODULE_STATUS_INITIALIZATION")] ModuleStatusInitialization = 0,
    [pbr::OriginalName("MODULE_STATUS_WORK")] ModuleStatusWork = 1,
    [pbr::OriginalName("MODULE_STATUS_ERROR")] ModuleStatusError = 2,
    [pbr::OriginalName("MODULE_STATUS_CONNECTION_ERROR")] ModuleStatusConnectionError = 3,
    [pbr::OriginalName("MODULE_STATUS_DISABLED")] ModuleStatusDisabled = 4,
  }

  public enum DriverStatusType {
    [pbr::OriginalName("DRIVER_STATUS_INITIALIZATION")] DriverStatusInitialization = 0,
    [pbr::OriginalName("DRIVER_STATUS_ERROR")] DriverStatusError = 1,
    [pbr::OriginalName("DRIVER_STATUS_CONNECTION_ERROR")] DriverStatusConnectionError = 2,
    [pbr::OriginalName("DRIVER_STATUS_DISABLED")] DriverStatusDisabled = 3,
    [pbr::OriginalName("DRIVER_STATUS_SLEEP")] DriverStatusSleep = 4,
    [pbr::OriginalName("DRIVER_STATUS_SETTING_POSITION")] DriverStatusSettingPosition = 5,
  }

  #endregion

}

#endregion Designer generated code
